DROP DATABASE IF EXISTS bugerDb;
CREATE DATABASE burgerDb;
USE bugerDb;

CREATE TABLE burgers (
    id INT AUTO_INCREMENT NOT NULL,
    burger VARCHAR(30) NOT NULL,
    consumed BOOLEAN DEFAULTF false,
    PRIMARY KEY(id)
);

