DROP DATABASE IF EXISTS burgerDb;
CREATE DATABASE burgerDb;
USE burgerDb;

CREATE TABLE burgers (
    id INT AUTO_INCREMENT NOT NULL,
    burger VARCHAR(30) NOT NULL,
    consume BOOLEAN DEFAULT false,
    PRIMARY KEY(id)
);

